const CONFIG = {
    introTitle: 'Hey boy!',
    introDesc: `Tớ có điều này muốn hỏi cậu nhớ phải trả lời thật lòng nhó`,
    btnIntro: 'Yep',
    title: 'Phải chăng cậu đã yêu ngay từ cái nhìn đầu tiên 😙',
    desc: 'Phải chăng cậu đã say ngay từ lúc thấy nụ cười ấy ',
    btnYes: 'Yêu ơi là yêuuu <33',
    btnNo: 'Không, cậu mơ à :3',
    question:'Trên thế giới hơn 7 tỉ người mà sao cậu lại thích tớ nhở <3',
    btnReply: 'Gửi cho cậu <3',
    reply: 'Yêu thì yêu mà không yêu thì yêu <33333333',
    mess: 'Tớ biết mà 🥰. Yêu cậu nhiều nhiều 😘😘',
    messDesc: 'Yêu thương nhưng từ từ hãng chén tớ nhé 😘😘.',
    btnAccept: 'Okiiiii lun <3',
}
