const CONFIG = {
    introTitle: 'Hey boy!',
    introDesc: `Tớ có điều này muốn hỏi cậu nhớ phải trả lời thật lòng nhó`,
    btnIntro: 'Yep',
    title: 'Cậu yêu tớ phải không 😙',
    desc: 'Nếu không trả lời mà thoát ra tức là cậu muốn làm chồng tớ rồi đó ',
    btnYes: 'Yêu ơi là yêuuu <33',
    btnNo: 'Không, cậu mơ à :3',
    question:'Trên thế giới hơn 7 tỉ người mà sao cậu lại thích tớ nhở <3',
    btnReply: 'Gửi cho cậu <3',
    reply: 'Yêu thì yêu mà không yêu thì yêu <33333333',
    mess: 'Tớ biết mà 🥰. Yêu cậu nhiều nhiều 😘😘',
    messDesc: 'Mình chọn cậu gòi. Chạy đâu cho tắt nắng :)',
    btnAccept: 'Okiiiii lun <3',
}
